[package]
name = "rustmaniax-sdk"
version = "0.1.0"
edition = "2024"
description = "Rust SDK for StepManiaX dance pad controllers"
license = "MIT"

[dependencies]
hidapi = { version = "2.6.5", default-features = false }
log = "0.4.29"
bytemuck = { version = "1.25.0", features = ["derive"] }
bitflags = "2.11.1"

[target.'cfg(target_os = "linux")'.dependencies]
hidapi = { version = "2.6.5", default-features = false, features = ["linux-static-hidraw"] }

[target.'cfg(target_os = "windows")'.dependencies]
hidapi = { version = "2.6.5", default-features = false, features = ["windows-native"] }

[dev-dependencies]
env_logger = "0.11.10"

[lints.clippy]
perf = { level = "warn", priority = -1 }
